version: '2.1'
services:
  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "80:80"
  backend:
    build:
      context: ./backend_hannah
      dockerfile: Dockerfile
    ports:
      - "8080:8080"