name: Padac

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pwd && ls
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the API and tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: python unit_tests.py
          start: flask run --host=0.0.0.0 --port=8080
          wait-on: "http://localhost:8080/api/v1/employees"
        env:
          FLASK_ENV: development

  push_to_dev:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Push to dev
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: Dev # Branche du merge
          FOLDER: backend-Padac # répertoire pour le back
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg} passed the tests with success"
